jupyterhub:
  singleuser:
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G
  auth:
    github:
      org_whitelist:
        - pangeo-ocean
    admin:
      access: true
      users:
        - raphaeldussin
        - rabernat
